spring:
  application:
    name: learn-graphql-java
  servlet:
    multipart:
      max-file-size: 2MB

server:
  http2:
    enabled: true

graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
    # specification and expectations of most clients, so use this option with caution
    introspection-enabled: true
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: true
    tracingEnabled: false